### ISSUE TITLE
Request for Instructions for Building

### ISSUE THREAD

**Issue by jlee335** [jwkim98/Motutapu#8]
Hello, I am interested in your project and trying to install it in my own PC. 
It will be very helpful if you can document the necessary requirements for installing and running the project.

**Comment by JustinKim98** [comment]
Sure, I will document it for you

Before that, I will briefly write instructions for you here
Try following these instructions
(Assuming Ubuntu or wsl)
1. git clone & git submodule init & git submodule update
2. cd Sapphire
3. python3 run_tests.py -d

These commands should work if you satisfied requirements

**Comment by jwkim98** [comment]
I documented it on the notion page (link present in README)
Please tell me if you have any issues installing and running tests

**Comment by jlee335** [comment]
Very helpful. Thank you
